# Generated by Django 5.1.3 on 2024-11-15 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_stanowisko_osoba_plec_osoba_stanowisko'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='ahe',
            new_name='age',
        ),
        migrations.AddField(
            model_name='osoba',
            name='data_dodania',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
