# Generated by Django 5.1.3 on 2024-12-20 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_osoba_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='stanowisko',
            options={'verbose_name_plural': 'Stanowiska'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AddField(
            model_name='person',
            name='firstname',
            field=models.CharField(default='Jan', max_length=60, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='lastname',
            field=models.CharField(default='Kowalski', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='osoba',
            name='data_dodania',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='imie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='nazwisko',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='plec',
            field=models.CharField(choices=[('k', 'kobieta'), ('m', 'mężczyzna'), ('i', 'inne')], default='k', max_length=1),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='stanowisko',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='myapp.stanowisko'),
        ),
        migrations.AlterField(
            model_name='person',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Choose your Team', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.team'),
        ),
    ]
